"""rename tool_models.name to category

Revision ID: 1b4d0666ee24
Revises: daab97bd76da
Create Date: 2026-04-25 12:00:16.671959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b4d0666ee24'
down_revision: Union[str, Sequence[str], None] = 'daab97bd76da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tool_models', sa.Column('category', sa.String(length=20), nullable=False))
    op.drop_column('tool_models', 'name')
    op.drop_constraint(op.f('tools_employee_id_fkey'), 'tools', type_='foreignkey')
    op.drop_column('tools', 'employee_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tools', sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('tools_employee_id_fkey'), 'tools', 'employees', ['employee_id'], ['id'])
    op.add_column('tool_models', sa.Column('name', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column('tool_models', 'category')
    # ### end Alembic commands ###
