"""add is_active Columns

Revision ID: daab97bd76da
Revises: 5e3b60a890a2
Create Date: 2026-03-28 23:51:58.827852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daab97bd76da'
down_revision: Union[str, Sequence[str], None] = '5e3b60a890a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('is_active',
                                         sa.Boolean(),
                                         nullable=False,
                                         server_default=sa.true()))
    op.add_column('locations', sa.Column('is_active',
                                         sa.Boolean(),
                                         nullable=False,
                                         server_default=sa.true()))
    op.add_column('tool_models', sa.Column('is_active',
                                           sa.Boolean(),
                                           nullable=False,
                                           server_default=sa.true()))
    op.add_column('tools', sa.Column('is_active',
                                     sa.Boolean(),
                                     nullable=False,
                                     server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tools', 'is_active')
    op.drop_column('tool_models', 'is_active')
    op.drop_column('locations', 'is_active')
    op.drop_column('employees', 'is_active')
    # ### end Alembic commands ###
