### =========================
### 1. Создать выдачу инструмента
### =========================
POST http://127.0.0.1:8000/tool-issues/
Content-Type: application/json

{
  "tool_id": 8,
  "employee_id": 8
}


### =========================
### 2. Создать другую выдачу
### =========================
POST http://127.0.0.1:8000/tool-issues/
Content-Type: application/json

{
  "tool_id": 2,
  "employee_id": 3
}


### =========================
### 3. Получить все активные выдачи (у сотрудников)
### =========================
GET http://127.0.0.1:8000/tool-issues/issued


### =========================
### 4. Получить все возвращённые инструменты
### =========================
GET http://127.0.0.1:8000/tool-issues/returned


### =========================
### 5. Получить выдачу по ID
### =========================
GET http://127.0.0.1:8000/tool-issues/1


### =========================
### 6. Вернуть инструмент (PATCH)
### =========================
PATCH http://127.0.0.1:8000/tool-issues/1