```http
### =========================================================
### TOOL MOVEMENTS TESTS
### =========================================================


### =========================================================
### 1. Создать перемещение инструмента
### Склад(id=1) -> Объект(id=3)
### =========================================================
POST http://127.0.0.1:8000/tool-movements/
Content-Type: application/json

{
  "tool_id": 9,
  "employee_id": 1,
  "from_location_id": 1,
  "to_location_id": 3
}


### =========================================================
### 2. Создать перемещение инструмента
### Объект(id=3) -> Ремонт(id=2)
### =========================================================
POST http://127.0.0.1:8000/tool-movements/
Content-Type: application/json

{
  "tool_id": 1,
  "employee_id": 2,
  "from_location_id": 3,
  "to_location_id": 2
}


### =========================================================
### 3. Создать перемещение инструмента
### Ремонт(id=2) -> Склад(id=1)
### =========================================================
POST http://127.0.0.1:8000/tool-movements/
Content-Type: application/json

{
  "tool_id": 4,
  "employee_id": 3,
  "from_location_id": 2,
  "to_location_id": 1
}


### =========================================================
### 4. Ошибка:
### инструмент не находится в указанной from_location
### =========================================================
POST http://127.0.0.1:8000/tool-movements/
Content-Type: application/json

{
  "tool_id": 1,
  "employee_id": 1,
  "from_location_id": 3,
  "to_location_id": 2
}


### =========================================================
### 5. Ошибка:
### несуществующий инструмент
### =========================================================
POST http://127.0.0.1:8000/tool-movements/
Content-Type: application/json

{
  "tool_id": 999,
  "employee_id": 1,
  "from_location_id": 1,
  "to_location_id": 2
}


### =========================================================
### 6. Ошибка:
### несуществующий сотрудник
### =========================================================
POST http://127.0.0.1:8000/tool-movements/
Content-Type: application/json

{
  "tool_id": 1,
  "employee_id": 999,
  "from_location_id": 1,
  "to_location_id": 2
}


### =========================================================
### 7. Ошибка:
### несуществующая from_location
### =========================================================
POST http://127.0.0.1:8000/tool-movements/
Content-Type: application/json

{
  "tool_id": 1,
  "employee_id": 1,
  "from_location_id": 999,
  "to_location_id": 2
}


### =========================================================
### 8. Ошибка:
### несуществующая to_location
### =========================================================
POST http://127.0.0.1:8000/tool-movements/
Content-Type: application/json

{
  "tool_id": 1,
  "employee_id": 1,
  "from_location_id": 1,
  "to_location_id": 999
}


### =========================================================
### 9. Получить все перемещения
### =========================================================
GET http://127.0.0.1:8000/tool-movements/


### =========================================================
### 10. Получить перемещение по id
### =========================================================
GET http://127.0.0.1:8000/tool-movements/1


### =========================================================
### 11. Ошибка:
### перемещение не найдено
### =========================================================
GET http://127.0.0.1:8000/tool-movements/999
```
